#!/usr/bin/env python3
# CI용: 환경 변수에서 프로젝트 루트의 config.py 생성 (GitHub Actions 등)
import os

REQUIRED_KEYS = [
    "NAVER_CLIENT_ID",
    "NAVER_CLIENT_SECRET",
    "NEWSAPI_KEY",
    "OPENAI_API_KEY",
    "NOTION_TOKEN",
    "NOTION_DATABASE_ID",
]

# GitHub Actions에서 생략 가능 — 비어 있으면 카카오 전송만 건너뜀
OPTIONAL_KEYS = [
    "KAKAO_REST_API_KEY",
    "KAKAO_CLIENT_SECRET",
    "KAKAO_ACCESS_TOKEN",
    "KAKAO_REFRESH_TOKEN",
]


def main():
    missing = [k for k in REQUIRED_KEYS if not os.environ.get(k)]
    if missing:
        raise SystemExit("Missing env vars: " + ", ".join(missing))

    root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    path = os.path.join(root, "config.py")
    lines = [
        "# Auto-generated by scripts/write_config_from_env.py (do not commit)",
        "",
    ]
    for k in REQUIRED_KEYS:
        lines.append(f"{k} = {repr(os.environ[k])}")
    for k in OPTIONAL_KEYS:
        lines.append(f"{k} = {repr(os.environ.get(k, ''))}")
    lines.append("")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("Wrote", path)


if __name__ == "__main__":
    main()
